repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: master
    hooks:
      - id: docker-compose-check

  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: df034f88cf92b394e6f00a78fa97a2aa4e270e60
    hooks:
      - id: check-poetry

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        language: system
        files: \.py$
        entry: poetry run ruff format
        pass_filenames: true

      - id: ruff-lint
        name: ruff lint
        language: system
        files: \.py$
        entry: poetry run ruff check --fix

      - id: check-coverage
        name: Check code coverage
        entry: coverage run --source='.' manage.py test --keepdb
        language: system
        pass_filenames: false
        stages: [push]
        fail_under: 75
